version: '3'

services:
  container1:
    image: python:3.12-slim
    container_name: container1
    command: tail -f /dev/null  # Keeps container running
    ports:
      - "80:22"  # Random port mapping for SSH
    environment:
      SSH_PASSWORD: password123
