services:
  marquez:
    image: marquezproject/marquez:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/marquez
      - DATABASE_USERNAME=marquez
      - DATABASE_PASSWORD=marquez
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: marquez
      POSTGRES_PASSWORD: marquez
      POSTGRES_DB: marquez
    restart: always

