services:
  marquez:
    image: marquezproject/marquez:latest
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/marquez
      - DATABASE_USERNAME=marquez
      - DATABASE_PASSWORD=marquez
    depends_on:
      - postgres
    restart: always
 
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: marquez
      POSTGRES_PASSWORD: marquez
      POSTGRES_DB: marquez
    restart: always
 
  marquez-web:
    image: marquezproject/marquez-web:latest
    ports:
      - "3000:3000"
    environment:
      - MARQUEZ_HOST=marquez
      - MARQUEZ_PORT=5000
    depends_on:
      - marquez
